### ISSUE TITLE
Configuration file defaults overridden

### ISSUE THREAD

**Issue by adamquaile** [netguru/capistrano-docker#6]
docker-compose by default will look for `docker-compose.yml` and `docker-compose.override.yml`. Am I right in thinking that by always specifying `-f docker-compose.yml` we lose that default functionality? 

https://docs.docker.com/compose/extends/

**Comment by rindek** [comment]
Hi @adamquaile 

Yes, it looks like you are correct. I did a little setup on my local, created two files, `docker-compose.yml` and `docker-compose.override.yml`. If I specified `-f docker-compose.yml` explicitly, then the `override` changes were not merged.

This is something that needs to be fixed. Thanks for the headsup, I'll look into it.

**Comment by adamquaile** [comment]
Thanks for checking - this is something I can have a go at fixing unless you get to it quickly/first. Would we omit the `-f` argument, or turn it into an array in cap (it is possible to specify arbitrarily many files, I think)?

**Comment by rindek** [comment]
@adamquaile my though was to
1. if `docker_compose_path` is not specified (is `nil`) then do not append `-f` option at all in tasks
2. specify a list of compose-files in an array

For now, for a very quick fix to your issue you could add in your configuration something like

`set :docker_compose_path, "docker-compose.yml -f docker-compose.override.yml"`

I will work on fixing this issue later today, so if you need a quick win you can use above line

**Comment by adamquaile** [comment]
@rindek Yes, that's what I have in my config, I just didn't like the idea of leaving it like that; it seemed a bit brittle. 

Thanks for looking into it.

**Comment by rindek** [comment]
@adamquaile  fixed in https://github.com/netguru/capistrano-docker/tree/v0.2.11 

Thanks for the bug report!

**Comment by adamquaile** [comment]
@rindek Nice, thanks for the quick fix.
